spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/iab-admin?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: user
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    timeout: 10000ms
    password: LDCldc
    lettuce:
      pool:
        max-active: 10
        min-idle: 5
        max-idle: 10
        max-wait: 30000ms
